allowBuilds:
  '@percy/core': true
  esbuild: true
  lefthook: true
  sharp: true
# Security settings
# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security
minimumReleaseAge: 10080 # 7 days
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
